all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: 10.0.40.101
          ansible_user: root
          ansible_become: false
    vms:
      hosts:
        docker-host:
          ansible_host: 10.0.40.102
        unifi-controller:
          ansible_host: 10.0.40.103
        ollama-gpu:
          ansible_host: 10.0.40.104
    pi:
      hosts:
        bernz-pi:
          ansible_host: 10.0.40.105
