---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    cputemp: true
    memory: true
    disk: /
    uptime: true
    units: imperial
    refresh: 3000

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hour12: true

